const ADMIN_FALLBACK={username:'sabrina',password_hash:'acf908e63e5551cd4de07054b641c1e009572696be86566a044e44435909313',role:'Administrator',name:'Sabrina Choirunnisa'};
const MONTHS=['Januari','Februari','Maret','April','Mei','Juni','Juli','Agustus','September','Oktober','November','Desember'];
const IDB_NAME='sim_spp_local',IDB_VERSION=1;
let db, admin=ADMIN_FALLBACK, currentSection='dashboard';
const $=id=>document.getElementById(id);
const money=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n||0);
const pad=n=>String(n).padStart(2,'0');
const period=(y,m)=>`${y}-${pad(m)}`;
async function sha256(text){const buf=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text));return [...new Uint8Array(buf)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(IDB_NAME,IDB_VERSION);r.onupgradeneeded=e=>{const d=e.target.result;if(!d.objectStoreNames.contains('students'))d.createObjectStore('students',{keyPath:'id'});if(!d.objectStoreNames.contains('bills')){const s=d.createObjectStore('bills',{keyPath:'id'});s.createIndex('period','period',{unique:false});s.createIndex('studentId','studentId',{unique:false})}if(!d.objectStoreNames.contains('payments')){const s=d.createObjectStore('payments',{keyPath:'id'});s.createIndex('period','period',{unique:false});s.createIndex('studentId','studentId',{unique:false})}};r.onsuccess=()=>{db=r.result;resolve(db)};r.onerror=()=>reject(r.error)})}
function tx(store,mode='readonly'){return db.transaction(store,mode).objectStore(store)}
function getAll(store){return new Promise((resolve,reject)=>{const r=tx(store).getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
function put(store,obj){return new Promise((resolve,reject)=>{const r=tx(store,'readwrite').put(obj);r.onsuccess=()=>resolve(obj);r.onerror=()=>reject(r.error)})}
function del(store,id){return new Promise((resolve,reject)=>{const r=tx(store,'readwrite').delete(id);r.onsuccess=()=>resolve();r.onerror=()=>reject(r.error)})}
function seed(){return Promise.all([getAll('students'),getAll('bills'),getAll('payments')]).then(async ([s,b,p])=>{if(!s.length){const data=[['001','Alya Putri','XII RPL 1',150000],['002','Bima Pratama','XII RPL 1',150000],['003','Citra Lestari','XI RPL 2',150000],['004','Daffa Ramadhan','XI TKJ 1',150000],['005','Eka Saputra','X RPL 1',150000],['006','Farah Nabila','X RPL 2',150000],['007','Gilang Akbar','X TKJ 1',150000],['008','Hana Zahra','X TKJ 2',150000]];for(const x of data)await put('students',{id:x[0],nis:x[0],name:x[1],className:x[2],monthly:x[3],status:'active',phone:'',createdAt:new Date().toISOString()})}if(!b.length){const now=new Date();const y=now.getFullYear(),m=now.getMonth()+1;const students=await getAll('students');for(const st of students.slice(0,6))await put('bills',{id:`${period(y,m)}-${st.id}`,studentId:st.id,period:period(y,m),amount:st.monthly,createdAt:new Date().toISOString()});const first=students[0];if(first)await put('payments',{id:`PAY-${Date.now()}`,studentId:first.id,period:period(y,m),amount:first.monthly,paidAt:new Date().toISOString(),method:'Tunai',note:'Pembayaran demo'})}})
async function loadAdmin(){try{const r=await fetch('data/admin.json',{cache:'no-store'});if(r.ok)admin=await r.json()}catch(e){admin=ADMIN_FALLBACK}}
function setYears(selectId){const el=$(selectId),y=new Date().getFullYear();el.innerHTML='';for(let i=y-2;i<=y+3;i++)el.insertAdjacentHTML('beforeend',`<option value="${i}">${i}</option>`)}
function setMonths(selectId,withAll=false){const el=$(selectId);el.innerHTML=(withAll?'<option value="all">Semua bulan</option>':'')+MONTHS.map((m,i)=>`<option value="${i+1}">${m}</option>`).join('')}
function initSelectors(){['dashboardMonth','billMonth','reportMonth'].forEach(x=>setMonths(x));setMonths('paymentMonthFilter',true);['dashboardYear','billYear','reportYear'].forEach(x=>setYears(x));const now=new Date();['dashboardMonth','billMonth','reportMonth'].forEach(x=>$(x).value=now.getMonth()+1);['dashboardYear','billYear','reportYear'].forEach(x=>$(x).value=now.getFullYear());$('paymentMonthFilter').value='all'}
function nav(){document.querySelectorAll('.nav-item[data-section]').forEach(b=>b.addEventListener('click',()=>showSection(b.dataset.section)));document.querySelectorAll('.link-btn[data-section]').forEach(b=>b.addEventListener('click',()=>showSection(b.dataset.section)))}
function showSection(id){currentSection=id;document.querySelectorAll('.section').forEach(s=>s.classList.toggle('active',s.id===id));document.querySelectorAll('.nav-item[data-section]').forEach(b=>b.classList.toggle('active',b.dataset.section===id));const titles={dashboard:['Dashboard','Ringkasan kondisi pembayaran SPP'],students:['Data Siswa','Kelola data siswa sebagai basis tagihan.'],bills:['Tagihan SPP','Buat dan pantau tagihan bulanan siswa.'],payments:['Pembayaran','Catat pembayaran dan lihat histori transaksi.'],arrears:['Tunggakan','Daftar siswa yang masih memiliki saldo tagihan.'],reports:['Laporan','Ringkasan pemasukan SPP dan histori pembayaran.']};$('pageTitle').textContent=titles[id][0];$('pageSubtitle').textContent=titles[id][1];renderCurrent()}
async function renderCurrent(){if(!db)return;if(currentSection==='dashboard')await renderDashboard();if(currentSection==='students')await renderStudents();if(currentSection==='bills')await renderBills();if(currentSection==='payments')await renderPayments();if(currentSection==='arrears')await renderArrears();if(currentSection==='reports')await renderReports()}
async function totalsFor(y,m){const per=period(y,m),[st,bills,pays]=await Promise.all([getAll('students'),getAll('bills'),getAll('payments')]);const active=st.filter(x=>x.status==='active');const bs=bills.filter(x=>x.period===per),ps=pays.filter(x=>x.period===per);let paidMap={};ps.forEach(x=>paidMap[x.studentId]=(paidMap[x.studentId]||0)+x.amount);let billed=0,paid=0,l=0,u=0,n=0;active.forEach(s=>{const b=bs.find(x=>x.studentId===s.id);if(!b){n++;return}billed+=b.amount;const p=paidMap[s.id]||0;paid+=p;if(p>=b.amount)l++;else u++});return {st,bs,ps,billed,paid,balance:Math.max(0,billed-paid),l,u,n,paidMap}} 
async function renderDashboard(){const y=+$('dashboardYear').value,m=+$('dashboardMonth').value,t=await totalsFor(y,m);$('statBilled').textContent=money(t.billed);$('statPaid').textContent=money(t.paid);$('statArrears').textContent=money(t.balance);$('statStudents').textContent=t.st.length;$('paidCount').textContent=t.l;$('unpaidCount').textContent=t.u;$('noneCount').textContent=t.n;const pct=t.billed?Math.round(t.paid/t.billed*100):0;$('paidPercent').textContent=pct+'%';$('statusCaption').textContent=`${MONTHS[m-1]} ${y}`;$('donut').style.background=`conic-gradient(var(--success) 0deg ${pct*3.6}deg,#e9edf4 ${pct*3.6}deg 360deg)`;const names=Object.fromEntries(t.st.map(s=>[s.id,s.name]));const rows=t.ps.sort((a,b)=>b.paidAt.localeCompare(a.paidAt)).slice(0,6).map(p=>`<tr><td><b>${p.id}</b></td><td>${names[p.studentId]||'-'}</td><td>${money(p.amount)}</td><td>${new Date(p.paidAt).toLocaleDateString('id-ID')}</td></tr>`).join('');$('recentPayments').innerHTML=rows?`<table><thead><tr><th>Transaksi</th><th>Siswa</th><th>Nominal</th><th>Tanggal</th></tr></thead><tbody>${rows}</tbody></table>`:'<div class="empty">Belum ada pembayaran pada periode ini.</div>'}
async function renderStudents(){const data=await getAll('students'),q=$('studentSearch').value.toLowerCase(),f=$('studentStatusFilter').value;const rows=data.filter(s=>(f==='all'||s.status===f)&&(`${s.nis} ${s.name} ${s.className}`).toLowerCase().includes(q)).sort((a,b)=>a.nis.localeCompare(b.nis)).map(s=>`<tr><td><b>${s.nis}</b></td><td>${s.name}</td><td>${s.className}</td><td>${money(s.monthly)}</td><td><span class="pill ${s.status}">${s.status==='active'?'Aktif':'Tidak aktif'}</span></td><td><button class="btn small-btn" onclick="editStudent('${s.id}')">Edit</button> <button class="danger-link" onclick="removeStudent('${s.id}')">Hapus</button></td></tr>`).join('');$('studentsTable').innerHTML=rows?`<table><thead><tr><th>NIS</th><th>Nama</th><th>Kelas</th><th>SPP/Bulan</th><th>Status</th><th>Aksi</th></tr></thead><tbody>${rows}</tbody></table>`:'<div class="empty">Data siswa belum tersedia.</div>'}
async function renderBills(){const y=+$('billYear').value,m=+$('billMonth').value,per=period(y,m),[st,bills,pays]=await Promise.all([getAll('students'),getAll('bills'),getAll('payments')]);const q=$('billSearch').value.toLowerCase(),filter=$('billStatusFilter').value;const map={};pays.filter(p=>p.period===per).forEach(p=>map[p.studentId]=(map[p.studentId]||0)+p.amount);const rows=st.filter(s=>s.status==='active').filter(s=>`${s.nis} ${s.name}`.toLowerCase().includes(q)).map(s=>{const b=bills.find(x=>x.studentId===s.id&&x.period===per),p=map[s.id]||0;if(!b)return filter==='all'||filter==='unpaid'?`<tr><td><b>${s.nis}</b></td><td>${s.name}</td><td>${s.className}</td><td>${money(s.monthly)}</td><td>-</td><td><span class="pill unpaid">Belum ditagih</span></td><td><button class="btn small-btn" onclick="createSingleBill('${s.id}')">Tagihkan</button></td></tr>`:'';let status=p>=b.amount?'paid':p>0?'partial':'unpaid';if(filter!=='all'&&filter!==status)return '';return `<tr><td><b>${s.nis}</b></td><td>${s.name}</td><td>${s.className}</td><td>${money(b.amount)}</td><td>${money(p)}</td><td><span class="pill ${status}">${status==='paid'?'Lunas':status==='partial'?'Sebagian':'Belum bayar'}</span></td><td><button class="btn small-btn" onclick="payFromBill('${b.id}')">Bayar</button></td></tr>`}).filter(Boolean).join('');$('billsTable').innerHTML=rows?`<table><thead><tr><th>NIS</th><th>Nama</th><th>Kelas</th><th>Tagihan</th><th>Terbayar</th><th>Status</th><th>Aksi</th></tr></thead><tbody>${rows}</tbody></table>`:'<div class="empty">Belum ada tagihan pada periode ini.</div>'}
async function renderPayments(){const [st,pays]=await Promise.all([getAll('students'),getAll('payments')]);const q=$('paymentSearch').value.toLowerCase(),mf=$('paymentMonthFilter').value, names=Object.fromEntries(st.map(s=>[s.id,s.name])),nises=Object.fromEntries(st.map(s=>[s.id,s.nis]));const rows=pays.filter(p=>(mf==='all'||p.period.split('-')[1]===pad(+mf))).filter(p=>`${p.id} ${nises[p.studentId]||''} ${names[p.studentId]||''}`.toLowerCase().includes(q)).sort((a,b)=>b.paidAt.localeCompare(a.paidAt)).map(p=>`<tr><td><b>${p.id}</b></td><td>${nises[p.studentId]||'-'}</td><td>${names[p.studentId]||'-'}</td><td>${MONTHS[+p.period.split('-')[1]-1]} ${p.period.slice(0,4)}</td><td>${money(p.amount)}</td><td>${p.method||'Tunai'}</td><td>${new Date(p.paidAt).toLocaleDateString('id-ID')}</td></tr>`).join('');$('paymentsTable').innerHTML=rows?`<table><thead><tr><th>Transaksi</th><th>NIS</th><th>Siswa</th><th>Periode</th><th>Nominal</th><th>Metode</th><th>Tanggal</th></tr></thead><tbody>${rows}</tbody></table>`:'<div class="empty">Belum ada transaksi pembayaran.</div>'}
async function renderArrears(){const [st,bills,pays]=await Promise.all([getAll('students'),getAll('bills'),getAll('payments')]);const paid={};pays.forEach(p=>paid[p.period+'|'+p.studentId]=(paid[p.period+'|'+p.studentId]||0)+p.amount);let rows=[],total=0,count=0;for(const b of bills){const s=st.find(x=>x.id===b.studentId);if(!s)continue;const p=paid[b.period+'|'+b.studentId]||0,bal=Math.max(0,b.amount-p);if(bal>0){total+=bal;count++;rows.push(`<tr><td><b>${s.nis}</b></td><td>${s.name}</td><td>${s.className}</td><td>${MONTHS[+b.period.split('-')[1]-1]} ${b.period.slice(0,4)}</td><td>${money(b.amount)}</td><td>${money(p)}</td><td><strong>${money(bal)}</strong></td></tr>`)}}$('arrearsSummary').innerHTML=`<div><span>Jumlah Siswa/Tagihan</span><b>${count}</b></div><div><span>Total Tunggakan</span><b>${money(total)}</b></div><div><span>Status</span><b>${count?'Perlu Ditindaklanjuti':'Tidak Ada Tunggakan'}</b></div>`;$('arrearsTable').innerHTML=rows.length?`<table><thead><tr><th>NIS</th><th>Siswa</th><th>Kelas</th><th>Periode</th><th>Tagihan</th><th>Terbayar</th><th>Sisa</th></tr></thead><tbody>${rows.sort().join('')}</tbody></table>`:'<div class="empty">Belum ada tunggakan.</div>'}
async function renderReports(){const perType=$('reportPeriod').value,y=+$('reportYear').value,m=+$('reportMonth').value;const [st,bills,pays]=await Promise.all([getAll('students'),getAll('bills'),getAll('payments')]);let bs=bills.filter(b=>b.period.startsWith(String(y))&&(perType==='year'||b.period===period(y,m))),ps=pays.filter(p=>p.period.startsWith(String(y))&&(perType==='year'||p.period===period(y,m)));let billed=bs.reduce((a,b)=>a+b.amount,0),paid=ps.reduce((a,b)=>a+b.amount,0);$('reportBilled').textContent=money(billed);$('reportPaid').textContent=money(paid);$('reportBalance').textContent=money(Math.max(0,billed-paid));$('reportTransactions').textContent=ps.length;const names=Object.fromEntries(st.map(s=>[s.id,s.name]));const rows=ps.sort((a,b)=>b.paidAt.localeCompare(a.paidAt)).map(p=>`<tr><td><b>${p.id}</b></td><td>${names[p.studentId]||'-'}</td><td>${MONTHS[+p.period.split('-')[1]-1]} ${p.period.slice(0,4)}</td><td>${money(p.amount)}</td><td>${new Date(p.paidAt).toLocaleDateString('id-ID')}</td></tr>`).join('');$('reportTable').innerHTML=rows?`<table><thead><tr><th>Transaksi</th><th>Siswa</th><th>Periode</th><th>Nominal</th><th>Tanggal</th></tr></thead><tbody>${rows}</tbody></table>`:'<div class="empty">Belum ada transaksi untuk laporan ini.</div>'}
function openModal(title,html){$('modalTitle').textContent=title;$('modalBody').innerHTML=html;$('modal').classList.remove('hidden')}$('modalClose').onclick=()=> $('modal').classList.add('hidden');
function showToast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
window.editStudent=async id=>{const s=(await getAll('students')).find(x=>x.id===id);openStudentForm(s)};window.removeStudent=async id=>{if(confirm('Hapus data siswa ini? Histori pembayaran dan tagihan tidak ikut terhapus.')){await del('students',id);await renderStudents();showToast('Data siswa dihapus')}};
function openStudentForm(s=null){openModal(s?'Edit Siswa':'Tambah Siswa',`<div class="modal-body"><div class="form-grid"><label>NIS<input id="fNis" value="${s?.nis||''}" ${s?'disabled':''}></label><label>Status<select id="fStatus"><option value="active" ${s?.status==='active'?'selected':''}>Aktif</option><option value="inactive" ${s?.status==='inactive'?'selected':''}>Tidak aktif</option></select></label><label class="full">Nama Lengkap<input id="fName" value="${s?.name||''}"></label><label>Kelas<input id="fClass" value="${s?.className||''}"></label><label>SPP / Bulan<input id="fMonthly" type="number" min="0" value="${s?.monthly||150000}"></label><label class="full">No. Telepon (opsional)<input id="fPhone" value="${s?.phone||''}"></label></div><div class="form-actions"><button class="btn" id="cancelModal">Batal</button><button class="btn btn-primary" id="saveStudent">Simpan</button></div></div>`);$('cancelModal').onclick=()=> $('modal').classList.add('hidden');$('saveStudent').onclick=async()=>{const obj={id:s?.id||$('fNis').value.trim(),nis:$('fNis').value.trim(),name:$('fName').value.trim(),className:$('fClass').value.trim(),monthly:+$('fMonthly').value||0,status:$('fStatus').value,phone:$('fPhone').value.trim(),createdAt:s?.createdAt||new Date().toISOString()};if(!obj.id||!obj.name){showToast('NIS dan nama wajib diisi');return}await put('students',obj);$('modal').classList.add('hidden');await renderStudents();showToast('Data siswa tersimpan')}}
async function generateBills(){const y=+$('billYear').value,m=+$('billMonth').value,per=period(y,m),students=await getAll('students'),bills=await getAll('bills');let count=0;for(const s of students.filter(x=>x.status==='active')){if(!bills.some(b=>b.id===`${per}-${s.id}`)){await put('bills',{id:`${per}-${s.id}`,studentId:s.id,period:per,amount:s.monthly,createdAt:new Date().toISOString()});count++}}showToast(`${count} tagihan berhasil dibuat`);await renderBills();}
window.createSingleBill=async id=>{const y=+$('billYear').value,m=+$('billMonth').value,per=period(y,m),s=(await getAll('students')).find(x=>x.id===id),exists=(await getAll('bills')).some(b=>b.id===`${per}-${id}`);if(!exists)await put('bills',{id:`${per}-${id}`,studentId:id,period:per,amount:s.monthly,createdAt:new Date().toISOString()});await renderBills();showToast('Tagihan dibuat')};
window.payFromBill=async billId=>{const b=(await getAll('bills')).find(x=>x.id===billId);openPaymentForm(b)};
async function openPaymentForm(bill=null){const students=await getAll('students');let selected=bill?.studentId||students[0]?.id||'';openModal('Catat Pembayaran',`<div class="modal-body"><div class="form-grid"><label class="full">Siswa<select id="pStudent">${students.filter(s=>s.status==='active').map(s=>`<option value="${s.id}" ${s.id===selected?'selected':''}>${s.nis} — ${s.name}</option>`).join('')}</select></label><label>Periode<input id="pPeriod" type="month" value="${bill?.period||period(new Date().getFullYear(),new Date().getMonth()+1)}"></label><label>Nominal<input id="pAmount" type="number" min="1" value="${bill?.amount||150000}"></label><label>Metode<select id="pMethod"><option>Tunai</option><option>Transfer</option><option>QRIS</option></select></label><label>Catatan<input id="pNote" value=""></label></div><div class="form-actions"><button class="btn" id="cancelPay">Batal</button><button class="btn btn-primary" id="savePay">Simpan Pembayaran</button></div></div>`);$('cancelPay').onclick=()=> $('modal').classList.add('hidden');$('savePay').onclick=async()=>{const id='PAY-'+Date.now();await put('payments',{id,studentId:$('pStudent').value,period:$('pPeriod').value,amount:+$('pAmount').value,paidAt:new Date().toISOString(),method:$('pMethod').value,note:$('pNote').value.trim()});$('modal').classList.add('hidden');showToast('Pembayaran berhasil dicatat');await renderCurrent()}}
async function exportData(){const [students,bills,payments]=await Promise.all([getAll('students'),getAll('bills'),getAll('payments')]);const blob=new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),students,bills,payments},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`backup-spp-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);showToast('Backup JSON berhasil dibuat')}
async function importData(file){const data=JSON.parse(await file.text());for(const s of data.students||[])await put('students',s);for(const b of data.bills||[])await put('bills',b);for(const p of data.payments||[])await put('payments',p);showToast('Data berhasil diimpor');await renderCurrent()}
async function boot(){await openDB();await seed();await loadAdmin();initSelectors();nav();$('adminName').textContent=admin.name||admin.username;$('loginForm').addEventListener('submit',async e=>{e.preventDefault();const u=$('username').value.trim(),p=await sha256($('password').value);if(u===admin.username&&p===admin.password_hash){$('loginScreen').classList.add('hidden');$('app').classList.remove('hidden');sessionStorage.setItem('sim_spp_auth','1');showSection('dashboard')}else $('loginError').textContent='Username atau password salah.'});if(sessionStorage.getItem('sim_spp_auth')==='1'){ $('loginScreen').classList.add('hidden');$('app').classList.remove('hidden') }
$('logoutBtn').onclick=()=>{sessionStorage.removeItem('sim_spp_auth');location.reload()};$('addStudentBtn').onclick=()=>openStudentForm();$('generateBillsBtn').onclick=generateBills;$('addPaymentBtn').onclick=()=>openPaymentForm();$('exportBtn').onclick=exportData;$('importInput').onchange=e=>e.target.files[0]&&importData(e.target.files[0]);$('printArrearsBtn').onclick=()=>printSection('Tunggakan',$('arrearsTable').innerHTML);$('printReportBtn').onclick=()=>printSection('Laporan SPP',$('reportTable').innerHTML);['dashboardMonth','dashboardYear'].forEach(x=>$(x).onchange=renderDashboard);['billMonth','billYear','billSearch','billStatusFilter'].forEach(x=>$(x).addEventListener($(x).tagName==='INPUT'?'input':'change',renderBills));['studentSearch','studentStatusFilter'].forEach(x=>$(x).addEventListener($(x).tagName==='INPUT'?'input':'change',renderStudents));['paymentSearch','paymentMonthFilter'].forEach(x=>$(x).addEventListener($(x).tagName==='INPUT'?'input':'change',renderPayments));['reportPeriod','reportMonth','reportYear'].forEach(x=>$(x).addEventListener('change',renderReports));}
}
function printSection(title,html){const w=window.open('','_blank','width=900,height=700');w.document.write(`<html><head><title>${title}</title><style>body{font-family:Arial;padding:28px}h1{font-size:20px}table{width:100%;border-collapse:collapse;font-size:12px}th,td{border:1px solid #ddd;padding:8px;text-align:left}th{background:#f4f6f9}</style></head><body><h1>${title}</h1><p>Dicetak: ${new Date().toLocaleString('id-ID')}</p>${html}</body></html>`);w.document.close();w.focus();w.print()}
boot();
