(function(){
  'use strict';
  const KEY='sim_spp_db_v3';
  const ADMIN=JSON.parse(document.getElementById('adminData').textContent);
  const months=['Januari','Februari','Maret','April','Mei','Juni','Juli','Agustus','September','Oktober','November','Desember'];
  const money=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n)||0);
  const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const uid=p=>p+Date.now().toString(36)+Math.random().toString(36).slice(2,7);
  const now=new Date(); const ym=now.getFullYear()+'-'+String(now.getMonth()+1).padStart(2,'0');
  function seed(){
    const students=[
      {id:'s1',nis:'24001',name:'Alya Putri',class:'XII RPL 1',major:'Rekayasa Perangkat Lunak',active:true},
      {id:'s2',nis:'24002',name:'Bima Pratama',class:'XII RPL 1',major:'Rekayasa Perangkat Lunak',active:true},
      {id:'s3',nis:'24003',name:'Citra Lestari',class:'XI TKJ 1',major:'Teknik Komputer Jaringan',active:true},
      {id:'s4',nis:'24004',name:'Dimas Saputra',class:'XI TKJ 1',major:'Teknik Komputer Jaringan',active:true},
      {id:'s5',nis:'24005',name:'Eka Ramadhan',class:'X RPL 1',major:'Rekayasa Perangkat Lunak',active:true}
    ];
    const rates=[{id:'r1',class:'X RPL 1',amount:150000,note:'SPP bulanan'},{id:'r2',class:'XI TKJ 1',amount:175000,note:'SPP bulanan'},{id:'r3',class:'XII RPL 1',amount:200000,note:'SPP bulanan'}];
    const bills=[]; const payments=[];
    const periods=[ym, previousYM(ym)];
    students.forEach((st,i)=>{ const rt=rates.find(r=>r.class===st.class)||rates[0]; periods.forEach((period,j)=>{bills.push({id:uid('b'),studentId:st.id,period,amount:rt.amount,paid:j===0&&i<3?rt.amount: j===1&&i===0?rt.amount:0});});});
    bills.forEach((b,i)=>{if(b.paid){payments.push({id:uid('p'),number:'TRX-'+String(1001+i),date:dateOnly(new Date()),studentId:b.studentId,billId:b.id,amount:b.paid,method:'Transfer',note:'Data demo'});}});
    return {students,rates,bills,payments};
  }
  function previousYM(v){let [y,m]=v.split('-').map(Number);m--;if(m===0){m=12;y--}return y+'-'+String(m).padStart(2,'0')}
  function dateOnly(d){return d.toISOString().slice(0,10)}
  let db=loadDB();
  function loadDB(){try{const x=JSON.parse(localStorage.getItem(KEY)||'null');return x&&x.students&&x.rates&&x.bills&&x.payments?x:seed()}catch(e){return seed()}}
  function save(){localStorage.setItem(KEY,JSON.stringify(db)); renderAll()}

  const loginScreen=document.getElementById('loginScreen'), app=document.getElementById('app');
  document.getElementById('loginForm').addEventListener('submit',e=>{e.preventDefault();const u=document.getElementById('username').value.trim(),p=document.getElementById('password').value; if(u===ADMIN.username&&p===ADMIN.password){sessionStorage.setItem('spp_auth','1');loginScreen.classList.add('hidden');app.classList.remove('hidden');initApp();}else document.getElementById('loginError').textContent='Username atau password salah.';});
  document.getElementById('logoutBtn').onclick=()=>{sessionStorage.removeItem('spp_auth');location.reload()};
  if(sessionStorage.getItem('spp_auth')==='1'){loginScreen.classList.add('hidden');app.classList.remove('hidden')}

  const pages={dashboard:['Dashboard','Ringkasan SPP sekolah'],students:['Data Siswa','Kelola siswa dan kelas'],rates:['Tarif SPP','Atur nominal SPP per kelas'],bills:['Tagihan SPP','Tagihan bulanan siswa'],payments:['Pembayaran','Catat pembayaran SPP'],history:['Histori','Riwayat pembayaran siswa'],arrears:['Tunggakan','Tagihan belum lunas'],reports:['Laporan','Rekap SPP']};
  function go(page){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active-page',x.id===page));document.querySelectorAll('.nav-item[data-page]').forEach(x=>x.classList.toggle('active',x.dataset.page===page));document.getElementById('pageTitle').textContent=pages[page][0];document.getElementById('pageSubtitle').textContent=pages[page][1];renderAll()}
  document.querySelectorAll('[data-page]').forEach(el=>el.addEventListener('click',()=>go(el.dataset.page)));
  document.getElementById('quickGenerate').onclick=()=>showGenerateModal(); document.getElementById('generateBtn').onclick=()=>showGenerateModal(); document.getElementById('addStudentBtn').onclick=()=>showStudentModal(); document.getElementById('addRateBtn').onclick=()=>showRateModal(); document.getElementById('addPaymentBtn').onclick=()=>showPaymentModal(); document.getElementById('printArrearsBtn').onclick=()=>printArrears(); document.getElementById('printReportBtn').onclick=()=>printReport();
  document.getElementById('closeModal').onclick=closeModal;
  function openModal(title,html,onSubmit){document.getElementById('modalTitle').textContent=title;document.getElementById('modalBody').innerHTML=html;document.getElementById('modal').classList.remove('hidden'); if(onSubmit)document.getElementById('modalForm').addEventListener('submit',e=>{e.preventDefault();onSubmit(new FormData(e.currentTarget))},{once:true})}
  function closeModal(){document.getElementById('modal').classList.add('hidden')}
  function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
  function classOptions(selected=''){return [...new Set(db.rates.map(r=>r.class))].map(c=>`<option ${c===selected?'selected':''}>${esc(c)}</option>`).join('')||'<option>X RPL 1</option>'}
  function studentOptions(selected=''){return db.students.filter(s=>s.active).map(s=>`<option value="${s.id}" ${s.id===selected?'selected':''}>${esc(s.nis)} - ${esc(s.name)}</option>`).join('')}
  function periodLabel(p){const [y,m]=p.split('-');return months[Number(m)-1]+' '+y}
  function showStudentModal(id){const s=db.students.find(x=>x.id===id);openModal(id?'Edit Siswa':'Tambah Siswa',`<form id="modalForm"><div class="form-grid"><label>NIS<input name="nis" required value="${esc(s?.nis||'')}"></label><label>Nama<input name="name" required value="${esc(s?.name||'')}"></label><label>Kelas<select name="class">${classOptions(s?.class)}</select></label><label>Jurusan<input name="major" value="${esc(s?.major||'')}"></label><label>Status<select name="active"><option value="1" ${s?.active!==false?'selected':''}>Aktif</option><option value="0" ${s?.active===false?'selected':''}>Nonaktif</option></select></label></div><div class="form-actions"><button type="button" class="btn" id="cancelModal">Batal</button><button class="btn primary">Simpan</button></div></form>`,fd=>{if(s){Object.assign(s,{nis:fd.get('nis'),name:fd.get('name'),class:fd.get('class'),major:fd.get('major'),active:fd.get('active')==='1'})}else db.students.push({id:uid('s'),nis:fd.get('nis'),name:fd.get('name'),class:fd.get('class'),major:fd.get('major'),active:fd.get('active')==='1'});save();closeModal();toast('Data siswa tersimpan')});document.getElementById('cancelModal').onclick=closeModal}
  function showRateModal(id){const r=db.rates.find(x=>x.id===id);openModal(id?'Edit Tarif':'Tambah Tarif',`<form id="modalForm"><div class="form-grid"><label>Kelas<input name="class" required value="${esc(r?.class||'')}"></label><label>Nominal SPP<input name="amount" type="number" min="0" required value="${r?.amount||150000}"></label><label class="full-field">Keterangan<input name="note" value="${esc(r?.note||'SPP bulanan')}"></label></div><div class="form-actions"><button type="button" class="btn" id="cancelModal">Batal</button><button class="btn primary">Simpan</button></div></form>`,fd=>{if(r)Object.assign(r,{class:fd.get('class'),amount:Number(fd.get('amount')),note:fd.get('note')});else db.rates.push({id:uid('r'),class:fd.get('class'),amount:Number(fd.get('amount')),note:fd.get('note')});save();closeModal();toast('Tarif tersimpan')});document.getElementById('cancelModal').onclick=closeModal}
  function showGenerateModal(){const defaultPeriod=ym;openModal('Generate Tagihan SPP',`<form id="modalForm"><div class="form-grid"><label>Periode<select name="period">${months.map((m,i)=>{const val=(now.getFullYear())+'-'+String(i+1).padStart(2,'0');return `<option value="${val}" ${val===defaultPeriod?'selected':''}>${m} ${now.getFullYear()}</option>`}).join('')}</select></label><label>Target<select name="target"><option value="all">Semua siswa aktif</option><option value="class">Satu kelas</option></select></label><label class="full-field">Kelas<select name="class">${classOptions()}</select></label></div><p class="muted">Tagihan yang sudah ada tidak akan diduplikasi.</p><div class="form-actions"><button type="button" class="btn" id="cancelModal">Batal</button><button class="btn primary">Generate</button></div></form>`,fd=>{const period=fd.get('period');const cls=fd.get('class');const targets=db.students.filter(s=>s.active&&(fd.get('target')==='all'||s.class===cls));let count=0;targets.forEach(s=>{if(!db.bills.some(b=>b.studentId===s.id&&b.period===period)){const r=db.rates.find(x=>x.class===s.class)||db.rates[0];if(r){db.bills.push({id:uid('b'),studentId:s.id,period,amount:r.amount,paid:0});count++}}});save();closeModal();toast(count+' tagihan berhasil dibuat')});document.getElementById('cancelModal').onclick=closeModal}
  function showPaymentModal(billId){const bill=db.bills.find(b=>b.id===billId);openModal('Catat Pembayaran',`<form id="modalForm"><div class="form-grid"><label>Siswa<select name="student" id="payStudent" required>${studentOptions(bill?.studentId)}</select></label><label>Tagihan<select name="bill" id="payBill" required></select></label><label>Jumlah<input name="amount" type="number" min="1" required></label><label>Metode<select name="method"><option>Tunai</option><option>Transfer</option><option>QRIS</option></select></label><label class="full-field">Catatan<input name="note" value=""></label></div><div class="form-actions"><button type="button" class="btn" id="cancelModal">Batal</button><button class="btn primary">Simpan Pembayaran</button></div></form>`,fd=>{const b=db.bills.find(x=>x.id===fd.get('bill'));const amount=Math.min(Number(fd.get('amount')),Math.max(0,b.amount-b.paid));if(!b||amount<=0){toast('Tagihan sudah lunas atau jumlah tidak valid');return}b.paid+=amount;db.payments.push({id:uid('p'),number:'TRX-'+String(Math.floor(100000+Math.random()*900000)),date:dateOnly(new Date()),studentId:fd.get('student'),billId:b.id,amount,method:fd.get('method'),note:fd.get('note')});save();closeModal();toast('Pembayaran berhasil dicatat')});
    const select=document.getElementById('payStudent'), billSel=document.getElementById('payBill');
    function fillBills(){const sid=select.value;const rows=db.bills.filter(b=>b.studentId===sid&&b.amount>b.paid);billSel.innerHTML=rows.map(b=>`<option value="${b.id}">${periodLabel(b.period)} • Sisa ${money(b.amount-b.paid)}</option>`).join('')||'<option value="">Tidak ada tunggakan</option>'; const b=db.bills.find(x=>x.id===billSel.value);document.querySelector('[name="amount"]').value=b?b.amount-b.paid:0}
    select.onchange=fillBills;fillBills();document.getElementById('cancelModal').onclick=closeModal;
  }
  function renderAll(){renderDashboard();renderStudents();renderRates();renderBills();renderPayments();renderHistory();renderArrears();renderReports()}
  function renderDashboard(){const active=db.students.filter(s=>s.active);const bills=db.bills.filter(b=>b.period===ym);const paid=db.payments.filter(p=>p.date.slice(0,7)===ym);const arrears=db.bills.filter(b=>b.amount>b.paid);document.getElementById('statStudents').textContent=active.length;document.getElementById('statBills').textContent=money(bills.reduce((a,b)=>a+b.amount,0));document.getElementById('statBillCount').textContent=bills.length+' tagihan';document.getElementById('statPaid').textContent=money(paid.reduce((a,p)=>a+p.amount,0));document.getElementById('statPayCount').textContent=paid.length+' transaksi';document.getElementById('statArrears').textContent=money(arrears.reduce((a,b)=>a+b.amount-b.paid,0));document.getElementById('statArrearCount').textContent=arrears.length+' tagihan';document.getElementById('recentPayments').innerHTML=paid.slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5).map(p=>{const s=db.students.find(x=>x.id===p.studentId);return `<div class="mini-row"><div><b>${esc(s?.name||'-')}</b><small>${esc(p.number)} • ${esc(p.method)}</small></div><b>${money(p.amount)}</b></div>`}).join('')||'<div class="empty">Belum ada pembayaran.</div>';document.getElementById('topArrears').innerHTML=arrears.slice().sort((a,b)=>(b.amount-b.paid)-(a.amount-a.paid)).slice(0,5).map(b=>{const s=db.students.find(x=>x.id===b.studentId);return `<div class="mini-row"><div><b>${esc(s?.name||'-')}</b><small>${periodLabel(b.period)}</small></div><b>${money(b.amount-b.paid)}</b></div>`}).join('')||'<div class="empty">Tidak ada tunggakan.</div>'}
  function renderStudents(){populateClass('studentClassFilter');const q=document.getElementById('studentSearch').value.toLowerCase(),c=document.getElementById('studentClassFilter').value;document.getElementById('studentsTable').innerHTML=db.students.filter(s=>(!q||s.nis.toLowerCase().includes(q)||s.name.toLowerCase().includes(q))&&(!c||s.class===c)).map(s=>`<tr><td>${esc(s.nis)}</td><td>${esc(s.name)}</td><td>${esc(s.class)}</td><td>${esc(s.major)}</td><td><span class="badge ${s.active?'ok':'off'}">${s.active?'Aktif':'Nonaktif'}</span></td><td><button class="action-btn" onclick="window.editStudent('${s.id}')">Edit</button><button class="action-btn danger" onclick="window.deleteStudent('${s.id}')">Hapus</button></td></tr>`).join('')||'<tr><td colspan="6" class="empty">Data siswa belum ada.</td></tr>'}
  function populateClass(id){const el=document.getElementById(id);if(!el)return;const val=el.value;el.innerHTML='<option value="">Semua Kelas</option>'+[...new Set(db.students.map(s=>s.class).concat(db.rates.map(r=>r.class)))].sort().map(c=>`<option ${c===val?'selected':''}>${esc(c)}</option>`).join('')}
  function renderRates(){document.getElementById('ratesTable').innerHTML=db.rates.map(r=>`<tr><td>${esc(r.class)}</td><td><b>${money(r.amount)}</b></td><td>${esc(r.note)}</td><td><button class="action-btn" onclick="window.editRate('${r.id}')">Edit</button><button class="action-btn danger" onclick="window.deleteRate('${r.id}')">Hapus</button></td></tr>`).join('')||'<tr><td colspan="4" class="empty">Belum ada tarif.</td></tr>'}
  function renderBills(){fillBillFilters();const q=document.getElementById('billSearch').value.toLowerCase(),m=document.getElementById('billMonthFilter').value,st=document.getElementById('billStatusFilter').value;document.getElementById('billsTable').innerHTML=db.bills.slice().sort((a,b)=>b.period.localeCompare(a.period)).filter(b=>{const s=db.students.find(x=>x.id===b.studentId);const status=b.paid>=b.amount?'Lunas':'Belum Lunas';return (!q||s?.name.toLowerCase().includes(q)||s?.nis.toLowerCase().includes(q))&&(!m||b.period===m)&&(!st||status===st)}).map(b=>{const s=db.students.find(x=>x.id===b.studentId);const status=b.paid>=b.amount;return `<tr><td>${periodLabel(b.period)}</td><td>${esc(s?.name||'-')}<small style="display:block;color:#718096">${esc(s?.nis||'')}</small></td><td>${esc(s?.class||'-')}</td><td>${money(b.amount)}</td><td>${money(b.paid)}</td><td><b>${money(Math.max(0,b.amount-b.paid))}</b></td><td><span class="badge ${status?'ok':'warn'}">${status?'Lunas':'Belum Lunas'}</span></td><td>${status?'':'<button class="action-btn" onclick="window.payBill(\''+b.id+'\')">Bayar</button>'}<button class="action-btn danger" onclick="window.deleteBill('${b.id}')">Hapus</button></td></tr>`}).join('')||'<tr><td colspan="8" class="empty">Tidak ada tagihan yang cocok.</td></tr>'}
  function fillBillFilters(){const el=document.getElementById('billMonthFilter');const val=el.value;const periods=[...new Set(db.bills.map(b=>b.period))].sort().reverse();el.innerHTML='<option value="">Semua Periode</option>'+periods.map(p=>`<option value="${p}" ${p===val?'selected':''}>${periodLabel(p)}</option>`).join('')}
  function renderPayments(){const el=document.getElementById('paymentMonthFilter');const val=el.value;const periods=[...new Set(db.payments.map(p=>p.date.slice(0,7)))].sort().reverse();el.innerHTML='<option value="">Semua Bulan</option>'+periods.map(p=>`<option value="${p}" ${p===val?'selected':''}>${periodLabel(p)}</option>`).join('');const q=document.getElementById('paymentSearch').value.toLowerCase(),m=el.value;document.getElementById('paymentsTable').innerHTML=db.payments.slice().sort((a,b)=>b.date.localeCompare(a.date)).filter(p=>{const s=db.students.find(x=>x.id===p.studentId);return (!q||p.number.toLowerCase().includes(q)||s?.name.toLowerCase().includes(q)||s?.nis.toLowerCase().includes(q))&&(!m||p.date.slice(0,7)===m)}).map(p=>{const s=db.students.find(x=>x.id===p.studentId);const b=db.bills.find(x=>x.id===p.billId);return `<tr><td>${esc(p.number)}</td><td>${esc(p.date)}</td><td>${esc(s?.name||'-')}</td><td>${b?periodLabel(b.period):'-'}</td><td><b>${money(p.amount)}</b></td><td>${esc(p.method)}</td><td><button class="action-btn" onclick="window.printReceipt('${p.id}')">Cetak</button></td></tr>`}).join('')||'<tr><td colspan="7" class="empty">Belum ada transaksi.</td></tr>'}
  function renderHistory(){
    const el=document.getElementById('historyStudentFilter');
    const val=el.value;
    el.innerHTML='<option value="">Pilih siswa</option>'+db.students.map(s=>`<option value="${s.id}" ${s.id===val?'selected':''}>${esc(s.nis)} - ${esc(s.name)}</option>`).join('');
    const sid=el.value;
    if(!sid){document.getElementById('historyContent').innerHTML='<div class="empty">Pilih siswa untuk melihat histori.</div>';return}
    const rows=db.payments.filter(p=>p.studentId===sid).sort((a,b)=>b.date.localeCompare(a.date));
    const s=db.students.find(x=>x.id===sid);
    let html=`<div class="panel-head"><div><h3>${esc(s.name)}</h3><p>${esc(s.nis)} • ${esc(s.class)}</p></div></div>`;
    if(rows.length){
      html+='<div class="table-wrap"><table><thead><tr><th>Tanggal</th><th>No. Transaksi</th><th>Periode</th><th>Jumlah</th><th>Metode</th></tr></thead><tbody>';
      html+=rows.map(p=>{const b=db.bills.find(x=>x.id===p.billId);return `<tr><td>${p.date}</td><td>${esc(p.number)}</td><td>${b?periodLabel(b.period):'-'}</td><td>${money(p.amount)}</td><td>${esc(p.method)}</td></tr>`}).join('');
      html+='</tbody></table></div>';
    }else html+='<div class="empty">Belum ada pembayaran untuk siswa ini.</div>';
    document.getElementById('historyContent').innerHTML=html;
  }
  function renderArrears(){populateClass('arrearClassFilter');const q=document.getElementById('arrearSearch').value.toLowerCase(),c=document.getElementById('arrearClassFilter').value;const rows=db.bills.filter(b=>b.amount>b.paid).map(b=>({b,s:db.students.find(x=>x.id===b.studentId)})).filter(x=>(!q||x.s?.name.toLowerCase().includes(q)||x.s?.nis.toLowerCase().includes(q))&&(!c||x.s?.class===c)).sort((a,b)=>(b.b.amount-b.b.paid)-(a.b.amount-a.b.paid));document.getElementById('arrearsTable').innerHTML=rows.map(({b,s})=>`<tr><td>${esc(s?.name||'-')}</td><td>${esc(s?.class||'-')}</td><td>${periodLabel(b.period)}</td><td>${money(b.amount)}</td><td>${money(b.paid)}</td><td><b>${money(b.amount-b.paid)}</b></td><td><span class="badge warn">Belum Lunas</span></td></tr>`).join('')||'<tr><td colspan="7" class="empty">Tidak ada tunggakan.</td></tr>'}
  function renderReports(){const m=document.getElementById('reportMonth').value||ym;const years=[...new Set(db.bills.map(b=>b.period.slice(0,4)).concat(db.payments.map(p=>p.date.slice(0,4))))].sort().reverse();const yrEl=document.getElementById('reportYear');const yr=yrEl.value||String(now.getFullYear());yrEl.innerHTML=years.map(y=>`<option ${y===yr?'selected':''}>${y}</option>`).join('');const periods=[...new Set(db.bills.map(b=>b.period))].sort();const selected= m||periods[0]||ym; if(!document.getElementById('reportMonth').options.length){document.getElementById('reportMonth').innerHTML=months.map((x,i)=>`<option value="${String(i+1).padStart(2,'0')}">${x}</option>`).join('')} const month2=document.getElementById('reportMonth').value||String(now.getMonth()+1).padStart(2,'0');const full=yr+'-'+month2;const bills=db.bills.filter(b=>b.period===full),pays=db.payments.filter(p=>p.date.slice(0,7)===full);document.getElementById('reportBilled').textContent=money(bills.reduce((a,b)=>a+b.amount,0));document.getElementById('reportPaid').textContent=money(pays.reduce((a,p)=>a+p.amount,0));document.getElementById('reportBalance').textContent=money(bills.reduce((a,b)=>a+b.amount,0)-pays.reduce((a,p)=>a+p.amount,0));document.getElementById('reportTxn').textContent=pays.length;const map={};bills.forEach(b=>{map[b.period]??={billed:0,paid:0,txn:0};map[b.period].billed+=b.amount;map[b.period].paid+=b.paid;pays.filter(p=>p.billId===b.id).forEach(p=>map[b.period].txn++)});document.getElementById('reportTable').innerHTML=Object.keys(map).sort().reverse().map(p=>`<tr><td>${periodLabel(p)}</td><td>${money(map[p].billed)}</td><td>${money(map[p].paid)}</td><td>${money(map[p].billed-map[p].paid)}</td><td>${map[p].txn}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">Belum ada data laporan.</td></tr>'}
  function initApp(){const rm=document.getElementById('reportMonth');if(!rm.options.length)rm.innerHTML=months.map((x,i)=>`<option value="${String(i+1).padStart(2,'0')}" ${i===now.getMonth()?'selected':''}>${x}</option>`).join('');['studentSearch','studentClassFilter','billSearch','billMonthFilter','billStatusFilter','paymentSearch','paymentMonthFilter','historyStudentFilter','arrearSearch','arrearClassFilter','reportMonth','reportYear'].forEach(id=>document.getElementById(id)?.addEventListener('input',renderAll));renderAll()}
  document.getElementById('studentSearch').addEventListener('input',renderStudents);document.getElementById('studentClassFilter').addEventListener('change',renderStudents);document.getElementById('billSearch').addEventListener('input',renderBills);document.getElementById('billMonthFilter').addEventListener('change',renderBills);document.getElementById('billStatusFilter').addEventListener('change',renderBills);document.getElementById('paymentSearch').addEventListener('input',renderPayments);document.getElementById('paymentMonthFilter').addEventListener('change',renderPayments);document.getElementById('historyStudentFilter').addEventListener('change',renderHistory);document.getElementById('arrearSearch').addEventListener('input',renderArrears);document.getElementById('arrearClassFilter').addEventListener('change',renderArrears);document.getElementById('reportMonth').addEventListener('change',renderReports);document.getElementById('reportYear').addEventListener('change',renderReports);
  window.editStudent=showStudentModal;window.deleteStudent=id=>{if(confirm('Hapus siswa ini? Data histori/tagihannya juga akan dihapus.')){db.students=db.students.filter(s=>s.id!==id);db.bills=db.bills.filter(b=>b.studentId!==id);db.payments=db.payments.filter(p=>p.studentId!==id);save();toast('Siswa dihapus')}};window.editRate=showRateModal;window.deleteRate=id=>{if(confirm('Hapus tarif ini?')){db.rates=db.rates.filter(r=>r.id!==id);save();toast('Tarif dihapus')}};window.payBill=showPaymentModal;window.deleteBill=id=>{if(confirm('Hapus tagihan ini? Transaksi terkait juga dihapus.')){db.bills=db.bills.filter(b=>b.id!==id);db.payments=db.payments.filter(p=>p.billId!==id);save();toast('Tagihan dihapus')}};
  window.printReceipt=id=>{const p=db.payments.find(x=>x.id===id),s=db.students.find(x=>x.id===p.studentId),b=db.bills.find(x=>x.id===p.billId);const w=window.open('','_blank');w.document.write(`<html><head><title>Bukti Pembayaran ${esc(p.number)}</title><style>body{font-family:Arial;max-width:560px;margin:30px auto}h2{text-align:center}.rline{display:flex;justify-content:space-between;padding:10px 0;border-bottom:1px dashed #999}</style></head><body><h2>BUKTI PEMBAYARAN SPP</h2><div class="rline"><span>No. Transaksi</span><b>${esc(p.number)}</b></div><div class="rline"><span>Tanggal</span><b>${esc(p.date)}</b></div><div class="rline"><span>Siswa</span><b>${esc(s?.name||'-')}</b></div><div class="rline"><span>NIS / Kelas</span><b>${esc(s?.nis||'-')} / ${esc(s?.class||'-')}</b></div><div class="rline"><span>Periode</span><b>${b?periodLabel(b.period):'-'}</b></div><div class="rline"><span>Jumlah</span><b>${money(p.amount)}</b></div><div class="rline"><span>Metode</span><b>${esc(p.method)}</b></div><p style="margin-top:40px;text-align:center">Terima kasih.</p><script>window.onload=()=>window.print()<\/script></body></html>`);w.document.close()};
  function printArrears(){const rows=db.bills.filter(b=>b.amount>b.paid);const w=window.open('','_blank');w.document.write(`<html><head><title>Laporan Tunggakan</title><style>body{font-family:Arial;margin:30px}table{width:100%;border-collapse:collapse}th,td{border:1px solid #bbb;padding:8px;text-align:left}h2{text-align:center}</style></head><body><h2>LAPORAN TUNGGAKAN SPP</h2><table><thead><tr><th>Siswa</th><th>Kelas</th><th>Periode</th><th>Tagihan</th><th>Terbayar</th><th>Sisa</th></tr></thead><tbody>${rows.map(b=>{const s=db.students.find(x=>x.id===b.studentId);return `<tr><td>${esc(s?.name||'-')}</td><td>${esc(s?.class||'-')}</td><td>${periodLabel(b.period)}</td><td>${money(b.amount)}</td><td>${money(b.paid)}</td><td>${money(b.amount-b.paid)}</td></tr>`}).join('')}</tbody></table><script>window.onload=()=>window.print()<\/script></body></html>`);w.document.close()}
  function printReport(){const month=document.getElementById('reportMonth').value,year=document.getElementById('reportYear').value||String(now.getFullYear()),period=year+'-'+month;const bills=db.bills.filter(b=>b.period===period),pays=db.payments.filter(p=>p.date.slice(0,7)===period);const w=window.open('','_blank');w.document.write(`<html><head><title>Laporan SPP ${periodLabel(period)}</title><style>body{font-family:Arial;margin:30px}table{width:100%;border-collapse:collapse}th,td{border:1px solid #bbb;padding:8px;text-align:left}h2{text-align:center}.tot{margin:16px 0}</style></head><body><h2>LAPORAN SPP ${periodLabel(period).toUpperCase()}</h2><div class="tot"><b>Total Tagihan:</b> ${money(bills.reduce((a,b)=>a+b.amount,0))} &nbsp; <b>Total Pembayaran:</b> ${money(pays.reduce((a,p)=>a+p.amount,0))}</div><table><thead><tr><th>Siswa</th><th>Tagihan</th><th>Terbayar</th><th>Sisa</th></tr></thead><tbody>${bills.map(b=>{const s=db.students.find(x=>x.id===b.studentId);return `<tr><td>${esc(s?.name||'-')}</td><td>${money(b.amount)}</td><td>${money(b.paid)}</td><td>${money(b.amount-b.paid)}</td></tr>`}).join('')}</tbody></table><script>window.onload=()=>window.print()<\/script></body></html>`);w.document.close()}
  document.getElementById('backupBtn').onclick=()=>{const blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='backup_spp_'+dateOnly(new Date())+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
  document.getElementById('restoreInput').addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!x.students||!x.rates||!x.bills||!x.payments)throw Error();db=x;save();toast('Backup berhasil diimpor')}catch(err){toast('File backup tidak valid')}};r.readAsText(f);e.target.value='' });
  document.querySelectorAll('.link-btn').forEach(x=>x.onclick=()=>go(x.dataset.page));
  if(!app.classList.contains('hidden'))initApp();
})();
